version: '3.5'

networks:
  default:
    external:
      name: global-network

volumes:
  mailhog_data:
    labels:
      protected: ''
  portainer_data:
    labels:
      protected: ''

services: 
  mailhog:
    build:
      context: './mailhog'
    restart: unless-stopped
    tty: true
    privileged: true
    container_name: mailhog
    command: ["-storage=maildir", "-maildir-path=/home/mailhog/maildir"]
    volumes:
      - mailhog_data:/home/mailhog/maildir
    ports:
      - "1025:1025"
      - "8025:8025"
      
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9999:9000
      - 8888:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  default-site:
    build:
      context: ./default-site
      dockerfile: ./Dockerfile
    expose:
      - 80
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: localhost
    container_name: default-site
  