networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./certs/cert.pem:/etc/traefik/cert.pem
      - ./certs/key.pem:/etc/traefik/key.pem
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.test`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.tls=true
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck --ping"]
      interval: 4s
      timeout: 4s
      retries: 8
      start_period: 4s

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    command: "-H unix:///var/run/docker.sock"
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.test`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.tls=true

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 1025:1025
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailpit.rule=Host(`mailpit.test`)
      - traefik.http.routers.mailpit.entrypoints=websecure
      - traefik.http.services.mailpit.loadbalancer.server.port=8025
      - traefik.http.routers.mailpit.tls=true
