version: "3.5"

networks:
  default:
    external:
      name: global-network

volumes:
  portainer_data:
    labels:
      - protected

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-proxy/vhosts.d:/etc/nginx/vhosts.d:ro

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    tty: true
    privileged: true
    container_name: global-mailhog
    ports:
      - "1125:1025"
      - "8125:8025"

  portainer:
    image: portainer/portainer-ce
    environment: 
      VIRTUAL_HOST: portainer.test
      VIRTUAL_PORT: 9000
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    #ports:
    #  - 9999:9000
    #  - 8888:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
