version: '3.5'

networks:
  default:
    external:
      name: global-network

volumes:
  # mailhog_data:
  portainer_data:

services: 
  # traefik:
  #   image: traefik:v2.3
  #   command:
  #     - "--log.level=DEBUG"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "8090:8080" # The Web UI (enabled by --api)
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  # mailhog:
  #   build:
  #     context: './mailhog'
  #   restart: unless-stopped
  #   tty: true
  #   privileged: true
  #   container_name: mailhog
  #   command: ["-storage=maildir", "-maildir-path=/home/mailhog/maildir"]
  #   volumes:
  #     - mailhog_data:/home/mailhog/maildir
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
      
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9999:9000
      - 8888:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx-proxy:
    build:
      context: './nginx-proxy'
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # default-site:
  #   build:
  #     context: ./default-site
  #     dockerfile: ./Dockerfile
  #   expose:
  #     - 80
  #   restart: unless-stopped
  #   environment:
  #     VIRTUAL_HOST: localhost
  #   container_name: default-site
  