version: "3"

networks:
  proxy:
    external: true

services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - './proxy/data:/data'
      - './proxy/letsencrypt:/etc/letsencrypt'
    environment:
      DB_SQLITE_FILE: '/data/database.sqlite'
    networks:
      - proxy
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8010:80/tcp"
    environment:
      TZ: 'Europe/Copenhagen'
      WEBPASSWORD: 'password'
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/:/etc/pihole/'
      - './dnsmasq/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
