version: "3.5"

networks:
  default:
    external:
      name: global-network

volumes:
  portainer_data:
    labels:
      - protected
  apt-cacher-ng:
    labels:
      - protected

services:
  nginx-proxy:
    build:
      context: "./nginx-proxy"
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    tty: true
    privileged: true
    container_name: global-mailhog
    ports:
      - "1125:1025"
      - "8125:8025"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9999:9000
      - 8888:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  apt-cacher-ng:
    image: sameersbn/apt-cacher-ng
    container_name: apt-cacher-ng
    ports:
      - "3142:3142"
    volumes:
      - apt-cacher-ng:/var/cache/apt-cacher-ng
    restart: always
