#!/usr/bin/env bash

# Function to check if mkcert is installed
check_mkcert_installed() {
    if ! command -v mkcert &>/dev/null; then
        echo "[Error] mkcert is not installed. Please install mkcert first."
        exit 1
    fi
}

# Function to install mkcert CA
install_mkcert_ca() {
    echo "[Info] Installing mkcert CA..."
    mkcert -install
}

# Function to load environment variables from .env file
load_domains() {
    if [ ! -f .domains ]; then
        echo "[Warning] .domains file not found. Please create it!"
        exit 1
    else
        set -a
        # shellcheck disable=SC2002
        DOMAINS=$(cat .domains)
        set +a
    fi
}

# Function to display domains to be loaded
display_domains() {
    local DOMAIN
    echo "[Info] Domains to load:"
    for DOMAIN in $DOMAINS; do
        echo " - ${DOMAIN}"
    done
}

# Function to generate certificates
generate_certs() {
    # shellcheck disable=SC2086
    mkcert -key-file certs/key.pem -cert-file certs/cert.pem $DOMAINS
}

restart_services() {
    # Restart services if needed
    echo "[Info] Restarting services..."
    # Uncomment and modify the following line to restart your service
    docker compose up -d
}

# Main script execution
main() {
    check_mkcert_installed
    install_mkcert_ca
    load_domains
    display_domains
    generate_certs
    restart_services
}

main
